name: dependabot-auto-merge

on:
  pull_request_target:
    branches:
      - 'dependabot/**'

permissions:
  packages: read
  pull-requests: write

jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
